version: '3'

services:
  db:
    build: .
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=snuggling-koala

  db-admin:
    image: "dpage/pgadmin4:4.2"
    depends_on:
      - db
    ports:
      - "127.0.0.1:5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
